feat: login system update
billchenchina/hitutil pull request #4
Opened 2022-01-14 07:40 UTC by Commiter16

Login system update, modify codes to fit changes.

2022-01-14 08:03 UTC, billchenchina requested changes

2022-01-14 08:03 UTC, billchenchina commented on hit/ids/login.py
> +    r2 = s.get('https://ids.hit.edu.cn/authserver/checkNeedCaptcha.htl',
```suggestion
    r2 = s.get('https://ids.hit.edu.cn/authserver/checkNeedCaptcha.html',
```
感觉应该是 html 才对？

2022-01-14 08:03 UTC, billchenchina commented on hit/ids/login.py
> +                   '_': round(time.time() * 1000)
下划线这个参数这个应该不需要？通常是用于浏览器防止缓存用的。

2022-01-14 08:13 UTC, billchenchina requested changes

2022-01-14 08:13 UTC, billchenchina commented on hit/ids/login.py
> +        'id="pwdEncryptSalt" value="(.*?)"').search(r1.text).groups()[0]
这个最好用 beautifulsoup 解析吧。。

2022-01-14 08:32 UTC, FerdinandSukhoi commented
ids现在是https了（

2022-01-14 08:33 UTC, billchenchina requested changes

2022-01-14 08:33 UTC, billchenchina commented on hit/ids/login.py
>      r1 = s.get('http://ids.hit.edu.cn/authserver/login')
```suggestion
    r1 = s.get('https://ids.hit.edu.cn/authserver/login')
```

2022-01-14 08:33 UTC, billchenchina commented on hit/ids/login.py
>      if r2.text == 'true':
这里似乎需要改成
```
    if json.loads(r.text)['isNeed']:
```

2022-01-14 08:33 UTC, billchenchina commented on hit/ids/login.py
> +        "cllt": "userNameLogin"
```suggestion
        "cllt": soup.find('input', {'name': 'cllt'})['value'],
```

2022-01-14 13:04 UTC, Commiter16 commented on hit/ids/login.py
> +                   '_': round(time.time() * 1000)
我没有学过网络编程相关知识，看到它请求的url里带了一串数字，猜是时间戳，验证了一下就加上了

2022-01-14 13:06 UTC, Commiter16 commented on hit/ids/login.py
> +        'id="pwdEncryptSalt" value="(.*?)"').search(r1.text).groups()[0]
这边我一开始也想跟下面的统一起来，但这个是hidden input，不是input，beautifulsoup好像没法直接搜出来，我就懒得改了，也能凑活用

2022-01-14 13:07 UTC, Commiter16 commented on hit/ids/login.py
>      if r2.text == 'true':
确实，因为一直返回的都是'isNeed': false，没进入分支，所以没发现

2022-01-14 13:08 UTC, Commiter16 commented on hit/ids/login.py
> +        "cllt": "userNameLogin"
这边的我一开始是这样写的，但是搜索结果是fidoLogin，会验证失败，所以硬编码进去了

2022-01-14 13:13 UTC, Commiter16 commented on hit/ids/login.py
> +    r2 = s.get('https://ids.hit.edu.cn/authserver/checkNeedCaptcha.htl',
我抓包显示是htl，我也感觉很奇怪......

2022-01-14 13:13 UTC, billchenchina commented on hit/ids/login.py
> +        'id="pwdEncryptSalt" value="(.*?)"').search(r1.text).groups()[0]
> 这边我一开始也想跟下面的统一起来，但这个是hidden input，不是input，beautifulsoup好像没法直接搜出来，我就懒得改了，也能凑活用

了解了，现在的 soup 范围太大了，应该让 soup 只搜 `#pwdFromId` 的 form

2022-01-14 13:18 UTC, billchenchina commented on hit/ids/login.py
> +    r2 = s.get('https://ids.hit.edu.cn/authserver/checkNeedCaptcha.htl',
我后来看了眼，确实是 htl。

2022-01-14 14:27 UTC, FerdinandSukhoi commented
获取验证码的url也有变动，https://ids.hit.edu.cn/authserver/getCaptcha.htl，不过我没有实际测试（但是读了源码）。其他变动欢迎参考我前两天写的https://github.com/HIT-ReFreSH/HitGeneralServices/commit/5a3e2689eb87f5d2b0f013e8193bbc5ed1655116（不过cookie那里疑似奇怪的bug

2022-01-14 15:19 UTC, Commiter16 commented
> 获取验证码的url也有变动，https://ids.hit.edu.cn/authserver/getCaptcha.htl ，不过我没有实际测试（但是读了源码）。其他变动欢迎参考我前两天写的 [HIT-ReFreSH/HitGeneralServices@5a3e268](https://github.com/HIT-ReFreSH/HitGeneralServices/commit/5a3e2689eb87f5d2b0f013e8193bbc5ed1655116) （不过cookie那里疑似是奇怪的bug，并非必要代码

Raise CaptchaNeeded跟运行失败对我来说没区别，这部分直接没管。
不过原来为什么没用开源库做个验证码识别与自动填写呢？是懒得搞还是怕做的太绝被喝茶？
看了你的代码，好像UA不同会有登录成功url上是personCenter还是personMobile的区别，当时没注意。

2022-01-14 15:54 UTC, FerdinandSukhoi commented
> > 获取验证码的url也有变动，https://ids.hit.edu.cn/authserver/getCaptcha.htl ，不过我没有实际测试（但是读了源码）。其他变动欢迎参考我前两天写的 [HIT-ReFreSH/HitGeneralServices@5a3e268](https://github.com/HIT-ReFreSH/HitGeneralServices/commit/5a3e2689eb87f5d2b0f013e8193bbc5ed1655116) （不过cookie那里疑似是奇怪的bug，并非必要代码
> 
> Raise CaptchaNeeded跟运行失败对我来说没区别，这部分直接没管。 不过原来为什么没用开源库做个验证码识别与自动填写呢？是懒得搞还是怕做的太绝被喝茶？ 看了你的代码，好像UA不同会有登录成功url上是personCenter还是personMobile的区别，当时没注意。

因为验证码不怎么出，，（实际上基本上不会出

2022-01-14 16:05 UTC, billchenchina commented
> 因为验证码不怎么出，，（实际上基本上不会出

好像只有错误登录三次才会出验证码的样子

2022-01-15 02:12 UTC, Commiter16 commented on hit/ids/login.py
> +    if r.url != 'https://ids.hit.edu.cn/personalInfo/personCenter/index.html':
根据UA不同，也许登录成功url会有一定区别，写成下面这样更好？
`if r.url not in ['https://ids.hit.edu.cn/personalInfo/personCenter/index.html', 'https://ids.hit.edu.cn/personalInfo/personalMobile/index.html']:`

2022-01-25 10:14 UTC, billchenchina commented
> 不过原来为什么没用开源库做个验证码识别与自动填写呢？是懒得搞还是怕做的太绝被喝茶？ 

因为解耦，验证码识别不应该由 hitutil 做

2022-01-25 10:24 UTC, billchenchina commented
滑块验证码的逻辑是

2022-01-25 10:26 UTC, billchenchina commented
滑块验证码看起来采用了 https://github.com/ArgoZhang/SliderCaptcha

验证码的逻辑是访问 https://ids.hit.edu.cn/authserver/common/openSliderCaptcha.htl 这个 URL，从中获得 `bigImage` 和 `smallImage`。滑动后通过 POST 请求发送 `canvasLength` 和 `moveLength` 到 https://ids.hit.edu.cn/authserver/common/verifySliderCaptcha.htl

2022-01-25 10:55 UTC, Commiter16 commented
差不多了的话作者合并一下？这几天都是自己修改后在本地跑的，没法在github workflow里直接install后调用了 @billchenchina

2022-01-25 11:04 UTC, billchenchina commented
> 差不多了的话作者合并一下？这几天都是自己修改后在本地跑的，没法在github workflow里直接install后调用了 @billchenchina

验证码先 raise NotImplementedError 吧，大概今晚发新版

2022-01-25 11:07 UTC, billchenchina commented
@Commiter16 方便留一个 E-mail 地址吗？我加到 Co-authored-by 里面。

2022-01-25 11:13 UTC, billchenchina approved these changes

2022-01-25 13:33 UTC, Commiter16 commented
> @Commiter16 方便留一个 E-mail 地址吗？我加到 Co-authored-by 里面。

很惭愧，只是做了一点微小的贡献🤓
nullrella@gmail.com

2022-01-25 13:44 UTC, billchenchina commented
> 很惭愧，只是做了一点微小的贡献🤓 [nullrella@gmail.com](mailto:nullrella@gmail.com)

看了一下好像不是你 GitHub 的公开 Email，我用 noreply 的 Email 了？

2022-01-25 14:50 UTC, merged